# Copyright © 2019-2022 The Pasts Contributors.
#
# Licensed under any of:
#  - Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
#  - MIT License (https://mit-license.org/)
#  - Boost Software License, Version 1.0 (https://www.boost.org/LICENSE_1_0.txt)
# At your choosing (See accompanying files LICENSE_APACHE_2_0.txt,
# LICENSE_MIT.txt and LICENSE_BOOST_1_0.txt).

[package]
name = "pasts"
version = "0.9.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR MIT OR BSL-1.0"
description = "Minimal and simpler alternative to the futures crate."
repository = "https://github.com/AldaronLau/pasts"
documentation = "https://docs.rs/pasts"
homepage = "https://github.com/AldaronLau/pasts/blob/stable/CHANGELOG.md"
include = ["Cargo.toml", "src/*", "README.md"]
keywords = ["futures", "platform-agnostic", "cross-platform", "io", "executor"]
categories = ["asynchronous", "embedded", "no-std", "rust-patterns", "wasm"]
readme = "README.md"
edition = "2018"

[dependencies]

[build-dependencies]

[dev-dependencies]
async-std = "1.0"

[features]
default = ["std"]
std = []
